export const REQUEST_COMPONENT = 'REQUEST_COMPONENT';
export const REQUEST_COMPONENT_SUCCESS = `REQUEST_COMPONENT_SUCCESS`;
export const REQUEST_COMPONENT_FAILURE= `REQUEST_COMPONENT_FAILURE`;
export const EDIT_PARAMETER = 'EDIT_PARAMETER';
export const SET_STATE = 'SET_STATE';
export const RELOAD = 'RELOAD';
export const APPLY = 'APPLY';
